spring.application.name=BusinessHouseGame
# suppress inspection "SpellCheckingInspection"
spring.datasource.url=jdbc:mysql://localhost:3306/businesshousegame
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
# suppress inspection "SpellCheckingInspection"
logging.level.com.ymd.businesshousegame=DEBUG
logging.level.org.hibernate=error

