CREATE TABLE BOARD (BOARD_ID INT AUTO_INCREMENT PRIMARY KEY);
create table BOARD_CELLS (BOARD_ID integer not null, BOARD_CELLS_ID integer not null unique);
CREATE TABLE CELL (HOTEL_OWNER_PLAYER_ID INTEGER UNIQUE,HOTEL_RENT INTEGER NOT NULL DEFAULT 50,HOTEL_WORTH INTEGER NOT NULL DEFAULT 200,ID INTEGER AUTO_INCREMENT,JAIL_PENALTY INTEGER NOT NULL DEFAULT 150,SEQUENCE_ON_BOARD  INTEGER NOT NULL, TREASURE_VALUE INTEGER NOT NULL DEFAULT 200,CELL_TYPE ENUM('EMPTY', 'HOTEL', 'JAIL', 'TREASURE') NOT NULL, PRIMARY KEY (ID));
CREATE TABLE DICE (ID INT AUTO_INCREMENT,LAST_USED_OUTPUT_INDEX INT NOT NULL,PRIMARY KEY (ID));
create table DICE_OUTPUTS (DICE_ID integer not null, OUTPUT integer);
CREATE TABLE GAME (BOARD_ID INT UNIQUE,DICE_ID INT UNIQUE,GAME_ID INT AUTO_INCREMENT,NEXT_PLAYER_PLAYER_ID INT UNIQUE,NUMBER_OF_TURNS_COMPLETED INT NOT NULL,STATUS ENUM('COMPLETED', 'CREATED', 'INPROGRESS'),PRIMARY KEY (GAME_ID));
create table GAME_PLAYERS (GAME_GAME_ID integer not null, PLAYERS_PLAYER_ID integer not null unique);
CREATE TABLE PLAYER (CURRENT_POSITION_ON_BOARD INT NOT NULL,PLAYER_ID INT AUTO_INCREMENT,PLAYER_POSITION INT NOT NULL,TOTAL_BALANCE INT NOT NULL,NAME VARCHAR(255),PRIMARY KEY (PLAYER_ID));


ALTER TABLE BOARD_CELLS ADD CONSTRAINT FK5al6eddedscmmdoqh9vxjfav8 FOREIGN KEY (BOARD_CELLS_ID) REFERENCES CELL(ID);
ALTER TABLE BOARD_CELLS ADD CONSTRAINT FKhul7w5t98tinc155b5bw1x4j8 FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID);
ALTER TABLE CELL ADD CONSTRAINT FK762594yoomjplvuisyerckcqw FOREIGN KEY (HOTEL_OWNER_PLAYER_ID) REFERENCES PLAYER(PLAYER_ID);
ALTER TABLE DICE_OUTPUTS ADD CONSTRAINT FKcjkhkbrpfyropxl9rk9l0rxsp FOREIGN KEY (DICE_ID) REFERENCES DICE(ID);
ALTER TABLE GAME ADD CONSTRAINT FKana02t2dv69dnew6d6gb2xx6a FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID);
ALTER TABLE GAME ADD CONSTRAINT FK7hjdfdnbwm8ma272d6f4ih8q2 FOREIGN KEY (DICE_ID) REFERENCES DICE(ID);
ALTER TABLE GAME ADD CONSTRAINT FKlldqstvhmqsgcnhe7bpro838a FOREIGN KEY (NEXT_PLAYER_PLAYER_ID) REFERENCES PLAYER(PLAYER_ID);
ALTER TABLE GAME_PLAYERS ADD CONSTRAINT FKey7nfyw2nv5o3dptg1ksi93vl FOREIGN KEY (PLAYERS_PLAYER_ID) REFERENCES PLAYER(PLAYER_ID);
ALTER TABLE GAME_PLAYERS ADD CONSTRAINT FKtaqwqj699sigdheaesl1idxk2 FOREIGN KEY (GAME_GAME_ID) REFERENCES GAME(GAME_ID);

