create table board (board_id integer generated by default as identity, primary key (board_id));
create table board_board_cells (board_board_id integer not null, board_cells_id integer not null unique);
create table cell (hotel_owner_player_id integer unique, hotel_rent integer not null, hotel_worth integer not null, id integer generated by default as identity, jail_penalty integer not null, sequence_on_board integer not null, treasure_value integer not null, cell_type enum ('EMPTY','HOTEL','JAIL','TREASURE'), primary key (id));
create table dice (id integer generated by default as identity, last_used_output_index integer not null, primary key (id));
create table dice_outputs (dice_id integer not null, output integer);
create table game (board_board_id integer unique, dice_id integer unique, game_id integer generated by default as identity, next_player_player_id integer unique, number_of_turns_completed integer not null, status enum ('COMPLETED','CREATED','INPROGRESS'), primary key (game_id));
create table game_players (game_game_id integer not null, players_player_id integer not null unique);
create table player (current_position_on_board integer not null, player_id integer generated by default as identity, player_position integer not null, total_balance integer not null, name varchar(255), primary key (player_id));


alter table if exists board_board_cells add constraint FK5al6eddedscmmdoqh9vxjfav8 foreign key (board_cells_id) references cell;
alter table if exists board_board_cells add constraint FKhul7w5t98tinc155b5bw1x4j8 foreign key (board_board_id) references board;
alter table if exists cell add constraint FK762594yoomjplvuisyerckcqw foreign key (hotel_owner_player_id) references player;
alter table if exists dice_outputs add constraint FKcjkhkbrpfyropxl9rk9l0rxsp foreign key (dice_id) references dice;
alter table if exists game add constraint FKana02t2dv69dnew6d6gb2xx6a foreign key (board_board_id) references board;
alter table if exists game add constraint FK7hjdfdnbwm8ma272d6f4ih8q2 foreign key (dice_id) references dice;
alter table if exists game add constraint FKlldqstvhmqsgcnhe7bpro838a foreign key (next_player_player_id) references player;
alter table if exists game_players add constraint FKey7nfyw2nv5o3dptg1ksi93vl foreign key (players_player_id) references player;
alter table if exists game_players add constraint FKtaqwqj699sigdheaesl1idxk2 foreign key (game_game_id) references game;
